name: jolobbi_app_new
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flutter_bloc: ^8.1.1
  flutter_google_places: ^0.3.0
  flutter_local_notifications: ^13.0.0
  flutter_secure_storage: ^7.0.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  local_auth: ^2.1.3
  pin_code_fields: ^7.4.0
  uuid: ^3.0.7
  webview_flutter: ^4.0.1
  shimmer: ^2.0.0
  flutter_screenutil: ^5.6.0
  get_it: ^7.2.0
  fpdart: ^0.4.0
  formz: ^0.4.1
  intl: ^0.17.0
  http: ^0.13.5
  geoflutterfire2: ^2.3.14
  geolocator: ^9.0.2
  flutter_dotenv: ^5.0.2
  flutter_paystack: ^1.0.7

dependency_overrides:
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/wallet/

    - assets/icons/
    - assets/icons/home/
    - assets/icons/wallet/
    - assets/icons/cart/

    - assets/svg/
    - assets/svg/wallet/
    - assets/svg/onboarding/

    - .env
